window.batchEntries = [
  ['ability','/əˈbɪləti/','名词（n.）','能力；才能；本领','able','able 是“能够”，ability 是“能够做到的能力”。','He showed great ability in solving difficult problems.','他在解决难题方面表现出很强的能力。'],
  ['able','/ˈeɪbəl/','形容词（adj.）','能够；有能力的；能干的','able','able to do 表示“能够做某事”。','She is able to explain the theory clearly.','她能够清楚地解释这个理论。'],
  ['aboard','/əˈbɔːd/','副词 / 介词（adv. / prep.）','在船（飞机、车）上；上船（飞机、车）','board','走上 board（交通工具），就是 aboard。','All passengers are now aboard the plane.','所有乘客现在都已登上飞机。'],
  ['abortion','/əˈbɔːʃən/','名词（n.）','流产；堕胎；（计划）失败','abort','abort 表示中止，abortion 是中止妊娠或计划。','The debate on abortion remains controversial.','关于堕胎的争论仍然很有争议。'],
  ['about','/əˈbaʊt/','介词 / 副词 / 形容词（prep. / adv. / adj.）','关于；大约；到处；即将','about','about 的核心是“在周围、关于”。','The book is about climate change.','这本书是关于气候变化的。'],
  ['above','/əˈbʌv/','介词 / 副词 / 形容词（prep. / adv. / adj.）','在上方；超过；上文的','above','above 表示位置或程度在更高处。','The temperature stayed above zero.','温度一直保持在零度以上。'],
  ['absence','/ˈæbsəns/','名词（n.）','缺席；不存在；缺乏','absent','absent 是不在场，absence 是不在场这一状态。','His absence was noticed immediately.','他的缺席很快被注意到。'],
  ['academic','/ˌækəˈdemɪk/','形容词 / 名词（adj. / n.）','学术的；学业的；大学教师','academy','academy 是学院，academic 是学院或学术相关的。','The paper has academic value.','这篇论文具有学术价值。'],
  ['academy','/əˈkædəmi/','名词（n.）','学院；研究院；学会','academy','把 academy 记作正式的学院或学术机构。','She studied at a military academy.','她在一所军事学院学习。'],
  ['accent','/ˈæksent/','名词 / 动词（n. / v.）','口音；重音；强调','accent','accent 是说话中的口音或被强调的音节。','Her British accent was easy to recognize.','她的英式口音很容易辨认。'],
  ['accept','/əkˈsept/','动词（v.）','接受；同意；承认','cept','cept 表示拿、接，accept 是接纳进来。','The committee accepted the proposal.','委员会接受了这项提议。'],
  ['accident','/ˈæksɪdənt/','名词（n.）','事故；意外；偶然的事','cid','accident 记作没有预料到的事件。','The accident blocked the main road.','事故堵塞了主干道。'],
  ['accommodate','/əˈkɒmədeɪt/','动词（v.）','容纳；提供住宿；适应','ac- + commod','commod 表示方便，accommodate 是提供方便或容纳。','The hotel can accommodate 200 guests.','这家酒店可以容纳 200 位客人。'],
  ['accord','/əˈkɔːd/','名词 / 动词（n. / v.）','一致；协议；给予','cord','accord 可联想 cord（心弦）一致，表示协调。','The two sides reached an accord.','双方达成了协议。'],
  ['account','/əˈkaʊnt/','名词 / 动词（n. / v.）','账户；说明；解释；占比','count','account 可理解为把事情 count（计算、说明）清楚。','The report accounts for the change.','这份报告解释了这一变化。'],
  ['accumulate','/əˈkjuːmjəleɪt/','动词（v.）','积累；积聚','cumul','cumul 表示堆积，accumulate 就是逐渐堆起来。','Dust accumulated on the shelves.','灰尘积聚在架子上。'],
  ['accurate','/ˈækjərət/','形容词（adj.）','准确的；精确的','cur','cur 表示关心、注意，认真注意才能准确。','The information must be accurate.','这些信息必须准确。'],
  ['accuse','/əˈkjuːz/','动词（v.）','指责；控告','cause','accuse somebody of 表示把责任或原因归给某人。','They accused him of lying.','他们指责他说谎。'],
  ['accustomed','/əˈkʌstəmd/','形容词（adj.）','习惯于；通常的','custom','custom 是习惯，accustomed to 是习惯于。','She is accustomed to working late.','她习惯于晚下班。'],
  ['achieve','/əˈtʃiːv/','动词（v.）','实现；达到；取得','chief','把目标做成 chief（最重要的成果），就是 achieve。','Hard work helped him achieve his goal.','努力帮助他实现了目标。'],
  ['acid','/ˈæsɪd/','名词 / 形容词（n. / adj.）','酸；酸性的；尖刻的','acid','acid 是酸，也可形容言语尖刻。','Acid rain damages the forest.','酸雨会破坏森林。'],
  ['acknowledge','/əkˈnɒlɪdʒ/','动词（v.）','承认；确认；致谢','knowledge','acknowledge 可记作承认自己 know（知道）某事。','He acknowledged the importance of evidence.','他承认证据的重要性。'],
  ['acquaint','/əˈkweɪnt/','动词（v.）','使熟悉；使了解','ac- + quaint','让某人与信息相识，be acquainted with 表示熟悉。','Please acquaint yourself with the rules.','请熟悉这些规则。'],
  ['acquire','/əˈkwaɪə/','动词（v.）','获得；学会；购得','quire','quire 有寻求、取得的联想，acquire 是获得到手。','Children acquire language naturally.','孩子自然地习得语言。'],
  ['acre','/ˈeɪkə/','名词（n.）','英亩','acre','acre 是土地面积单位，约 4047 平方米。','The farm covers 100 acres.','这个农场占地 100 英亩。'],
  ['acute','/əˈkjuːt/','形容词（adj.）','严重的；敏锐的；急性的；尖锐的','acut','acut 表示尖，尖锐可引申为敏锐或严重。','The shortage has become acute.','短缺已经变得严重。'],
  ['adapt','/əˈdæpt/','动词（v.）','适应；改编','apt','apt 表示合适，adapt 是调整到合适的状态。','Animals adapt to their environment.','动物适应它们的环境。'],
  ['addict','/əˈdɪkt/','名词 / 动词（n. / v.）','上瘾者；使上瘾','dict','addict 可理解为被某件事“说服并绑定”，形成瘾。','He became addicted to online games.','他沉迷于网络游戏。'],
  ['address','/əˈdres/','名词 / 动词（n. / v.）','地址；演讲；处理；致函','dress','address 可记作把问题直接“穿上、面对”，即处理。','The report addresses the main problem.','这份报告处理了主要问题。'],
  ['adequate','/ˈædɪkwət/','形容词（adj.）','足够的；适当的','equ','equ 表示相等，adequate 表示达到所需标准。','The evidence is adequate for a decision.','这些证据足以作出决定。'],
  ['adhere','/ədˈhɪə/','动词（v.）','坚持；遵守；粘附','here','adhere to 可记作坚持在规则 here（这里）之内。','All staff must adhere to the policy.','所有员工都必须遵守这项政策。'],
  ['adjacent','/əˈdʒeɪsənt/','形容词（adj.）','邻近的；毗连的','jac','adjacent 表示紧挨着、相邻的。','The rooms are adjacent to each other.','这些房间彼此相邻。'],
  ['adjust','/əˈdʒʌst/','动词（v.）','调整；适应；校准','just','adjust 是把东西调到 just（恰好合适）。','You can adjust the seat height.','你可以调整座椅高度。'],
  ['administer','/ədˈmɪnɪstə/','动词（v.）','管理；实施；给予（药物）','minister','minister 是管理者，administer 是执行管理或实施。','The nurse administered the medicine.','护士给病人服用了药物。'],
  ['admire','/ədˈmaɪə/','动词（v.）','钦佩；欣赏','mir','mir 表示惊奇，admire 是因优秀而惊叹、钦佩。','I admire her courage.','我钦佩她的勇气。'],
  ['admission','/ədˈmɪʃən/','名词（n.）','进入；入场费；承认；录取','mit','mit 表示送入，admission 是进入或承认。','Admission to the museum is free.','博物馆免费入场。']
].map(([word,phonetic,pos,meaning,root,mnemonic,exampleEn,exampleZh],i)=>({
  id:2000+i,word,phonetic,pos,meaning,parts:[[root,'核心联想']],origin:`围绕 ${root} 进行词形联想；此处不强行断言为现代可拆前缀。`,mnemonic,
  collocations:[],note:'考研优先掌握该词的核心义和例句。',exampleEn,exampleZh,storyEn:'',storyZh:'',audioGb:'',audioUs:''
}));
